{% set name = "seamm-ff-util" %}
{% set version = "2023.2.6" %}
{% set sha256 = "4739f0d8b9ce610a3a2a75a26791d6bfa153937bcf1f618d711fffd664a761cb" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/seamm-ff-util/seamm_ff_util-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - molsystem
    - packaging
    - python >=3.8
    - seamm-util

test:
  imports:
    - seamm_ff_util
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/molssi-seam/seamm_ff_util
  summary: Utilities for handling forcefields in the SEAMM environment.
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://molssi-seamm.github.io/seamm_ff_util/

extra:
  recipe-maintainers:
    - paulsaxe
