{% set name = "seamm-ff-util" %}
{% set version = "2025.1.21" %}
{% set sha256 = "fdb5d06f0092ca1ff06a839ad68b3161860840ebc91e67273d5421ba86025d62" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/seamm-ff-util/seamm_ff_util-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - molsystem
    - numpy
    - packaging
    - python >=3.8
    - seamm-util
    - sympy

test:
  imports:
    - numpy
    - seamm_ff_util
    - sympy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/molssi-seam/seamm_ff_util
  summary: Utilities for handling forcefields in the SEAMM environment.
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://molssi-seamm.github.io/seamm_ff_util/

extra:
  recipe-maintainers:
    - paulsaxe
